apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system # Ensure the namespace correct
spec:
  template:
    spec:
      containers:
      - name: manager # instance name is must
        imagePullPolicy: Never #